title: Animal Clicker - E. Bamba
email: ebamba@bitsnshine.com
description: >- # this means to ignore newlines until "baseurl:"
  Cat clicker project for the Google-Udacity Nanodegree
baseurl: "" # the subpath of your site, e.g. /blog
url: "ebits.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter: ebamba
github: ebitsdev
linkedin: https://www.linkedin.com/in/emmanuelbamba/
gitrepo: udacity-fend-restaurant-review
host: localhost
port: 8080 #Use this port for the service worker to properly function on localhost

# Build settings
markdown: kramdown
plugins:
  # - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
